server:
  ip: 5.7.8.10
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/healthapp
    userName: developer
    password: Thirra1401!
#logging:
#  level: DEBUG
#  org.springframework.security: DEBUG